### DISCUSSION TITLE
Occasionally getting timeout from CoreDNS causing CertManager to fail

### DISCUSSION THREAD

**Discussion by TobiasDeBruijn** [coredns/coredns#4783] [Q&A]
I'm running a Kubernetes 1.21.3 cluster, freshly set up. I've noticed DNS issues causing CertManager to fail to issue certificates.

CoreDNS' upstream server is `10.10.0.1`, running on my router, which has `1.1.1.1` as it's upstream resolver. I'm unable to bypass this resolver as I require split-brain DNS. The upstream server appears completely stable, never returning a time out. 

So after starting an Ubuntu container with dig:
```
Every 0.5s: dig google.com @10.80.4.10                                                                                                                                                                                                                  ubuntu: Fri Aug  6 18:15:55 2021


; <<>> DiG 9.16.1-Ubuntu <<>> google.com @10.80.4.10
;; global options: +cmd
;; connection timed out; no servers could be reached
```
Where `10.80.4.10` is the Cluster IP of coredns.

My Kubeadm init is as follows: ``kubeadm init --upload-certs --pod-network-cidr 172.17.0.0/16 --service-cidr 10.80.4.0/22 --control-plane-endpoint kube-control.intern.array21.dev``, where `control-plane-endpoint kube-control.intern.array21.dev` resolves to `10.10.4.254`, which is a keepalived IP address for the master nodes.

I'm using Calico as my CNI with the following config:
```yaml
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
    - blockSize: 26
      cidr: 172.17.0.0/16
      encapsulation: VXLANCrossSubnet
      natOutgoing: Enabled
      nodeSelector: all()
```

So then for the question, what could be causing this? Is it something in CoreDNS, Calico, or potentially even my network itself?
Might be noteworthy, I do not have support for NAT Hairpinning/NAT Reflection on my network, though I'm unsure if that affects anything.

Thanks!

**Comment by chrisohaver** [comment]
If coredns pods are not receiving requests, it could be due to unready pods, or network issues ...

Have you run through https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/ ?

**Reply by TobiasDeBruijn** [reply]
Interestingly, it does occasionally receive requests, which is also evident from the logs it produces.

I'd say 1/4th of the requests fail, the rest is OK. Not sure what's up with that.

I've run through that guide top to bottom, back and front and bottom to top again, nothing in there that showed anything out of the ordinary

**Reply by chrisohaver** [reply]
OK, then CoreDNS is probably not the culprit.

If you are running > 1 CoreDNS replica, try targeting each CoreDNS pod ip with dig?

(to see if some pods are affected more than others)

**Reply by TobiasDeBruijn** [reply]
After creating an `ubuntu:latest` Pod in the `kube-system` namespace, installing `dnsutils` and querying for `google.com` on the individual servers, it indeed appears one pod is functional, while the other is fully dysfunctional. Lets call dns1 the working pod, and dns2 the dysfunctional one. 

dns1 runs on w3, dns2 runs on m3 (a worker and master respectively)
w3's netplan:
```yaml
network:
  version: 2
  ethernets:
    enp5s0:
      addresses: [10.10.4.27/16]
      gateway4: 10.10.0.1
      dhcp4: false
      dhcp6: false
      nameservers:
        addresses: [10.10.0.1]
```
m3's netplan:
```yaml
network:
  version: 2
  ethernets:
    enp5s0:
      addresses: [10.10.4.24/16]
      gateway4: 10.10.0.1
      dhcp4: false
      dhcp6: false
      nameservers:
        addresses: [10.10.0.1]
```
They're both identical save for the IP address, so I don't think the issue lies there. Both run `dig google.com @10.10.0.1` fine too, no issues there. The only real difference between the two is one is a master (and is broken), while the working one runs on a worker
