### DISCUSSION TITLE
Coredns waiting on kubernetes indefinitely

### DISCUSSION THREAD

**Discussion by vmarchaud** [coredns/coredns#4990] [Q&A] [answered]
Hi ! I'm trying to deploy coredns on a self managed kubernetes cluster (v1.21.4), i'm using the official helm chart (version 1.8.4) with the following values:
```yml
service:
    clusterIP: "172.16.255.42"
  serviceAccount:
    create: true
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 2
    metrics: []
  servers:
  - zones:
    - zone: .
    port: 53
    plugins:
    - name: errors
    - name: health
      configBlock: |-
        lameduck 5s
    - name: ready
    - name: kubernetes
      parameters: cluster.local 172.16.0.0/16 in-addr.arpa ip6.arpa
      configBlock: |-
        pods verified
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . 1.1.1.1 9.9.9.9
    - name: cache
      parameters: 30
    - name: loop
    - name: reload
    - name: loadbalance
    - name: autopath
      parameters: "@kubernetes"
```
Note that if i remove the kubernetes plugin, its work without issue (without internal resolving ofc). Also i've tried to increase verbosity with `debug` and `log` plugin without any issue (i saw afterwards that the kubernetes plugin contains almost no debug log).

Here are the log from the pod itself:
```
root@k8s-controller-1:/home/debian# kubectl logs coredns-coredns-58f47c98c8-mkpqd -n kube-system -f
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:53
[INFO] plugin/reload: Running configuration MD5 = 40faa7581f217ba0ea6e3019d2adfa0f
CoreDNS-1.8.4
linux/amd64, go1.16.4, 053c4d5
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
```

I'm guessing that coredns can't fetch data from the kubernetes api but i can't understand why, i've tried to reach the api from another pod without issue:
```
root@my-nginx-5b56ccd65f-n5ggz:/# curl -k https://172.16.255.1    
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

I also have checked logs for the apiserver but there is no errors or anything that links to a potential coredns request.
Some more information about my setup:
- every k8s component run on a wireguard private network (using 10.0.0.0/8 range)
- k8s pod ip are configured to use 172.16.0.0/17 and service uses 172.16.255.0/24
- cilium (v1.10.4) is configured and networking is fine across node & pods)
- I've only one worker node for my test (one cilium agent, one cilium operator, 2 nginx pod to test networking and the coredns pod)

I've looked around everywhere that i could think of without having luck, does anyone have an idea to debug this further ?
Thanks in advance
