### DISCUSSION TITLE
Domain resolution for docker containers

### DISCUSSION THREAD

**Discussion by nikhiljohn10** [coredns/coredns#5643] [Q&A]
# Question

How to configure CoreDNS in a docker environment with the least host adjustments?

### Docker compose file of CoreDNS
```
version: '3.9'

services:

  coredns:
    image: coredns/coredns:1.10.0
    container_name: coredns
    restart: always
    network_mode: host
    command: -conf /data/Corefile -dns.port 53
    ports:
      - 127.0.0.1:53:53
      - 127.0.0.1:53:53/udp
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./data:/data
      - config:/etc/coredns
    dns:
      - 1.1.1.1
      - 8.8.8.8

volumes:
  config:
```

### Corefile

```
. {
    forward . /etc/resolv.conf
    reload 5s 2s
    log
    errors
}

ripples:53 {
    file /data/db.ripples
    log
    errors
}
```

### DNS Record

```
$ORIGIN ripples.
$TTL 1h

; ====================== Resource Records =====================

@	    IN	SOA     dns.ripples. admin.ripples. (
                        2017042745      ; serial
                        1d              ; refresh
                        1h              ; retry
                        2w              ; expire
                        1h)             ; minimum

 	    IN  NS      dns.ripples.
            IN  A       172.28.0.3
dns         IN  A       127.0.0.1
ca          IN  A       172.28.0.2
```

This is working correctly on the host side when the host's DNS server is set to `127.0.0.1`.
But I also need the containers running on the host to resolve the DNS queries using the same CoreDNS server(container) as well.

Is there any possible method to do it?
