### DISCUSSION TITLE
Wildcard DNS using Template Plugin

### DISCUSSION THREAD

**Discussion by patrickap** [coredns/coredns#6349] [General]
I am experiencing a problem with the latest version of CoreDNS. I'm using the template plugin to create a wildcard DNS entry. It was working perfectly in version 1.10.1, but fails in version 1.11.1. I'm wondering if there's something I need to adjust. Additionally, the browser indicates an 'invalid request' error. Thank you in advance.

docker-compose.yml
```yml
version: "3.7"

services:
  coredns:
    container_name: coredns
    image: coredns/coredns:1.11.1
    environment:
      - HOST_IP=${HOST_IP?}
      - HOST_NAME=${HOST_NAME?}
    init: true
    restart: always
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./Corefile:/Corefile:ro
```

Corefile
```
. {
  forward . 8.8.8.8

  template IN A {$HOST_NAME} {
    match ^(.*)$
    answer "{{ .Name }} 300 IN A {$HOST_IP}"
    fallthrough
  }

  log
  health
  errors
}
```
