### DISCUSSION TITLE
Setup the unbound or forwards plugin for recursion.

### DISCUSSION THREAD

**Discussion by chris-edwards-pub** [coredns/coredns#6619] [Q&A]
Hello!

I am trying to migrate from bind to coredns because its containerized.   I need coredns to do "recursion yes;" like bind does or to forward the query on to a specified server.   Basically we have private DNS or split DNS .  I tried the following without success. 

With forward:
```
example.org {
    file /zones/example.org.zone {
        reload 5s
    }
    forward . 8.8.8.8
}
```
With unbound:
```
example.org {
    file /zones/example.org.zone {
        reload 5s
    }
    unbound {
        config /unbound.conf
    }
}
```
unbound.conf
```
server:
    log-queries: yes
forward-zone:
    name: "."
    forward-addr: 8.8.8.8
```

Any help is greatly appreciated.

Thanks, 

Chris
