### DISCUSSION TITLE
CoreDNS primary-secondary setup cannot resolve kubernetes service

### DISCUSSION THREAD

**Discussion by Marfien** [coredns/coredns#6976] [Q&A]
Hello there!

I am trying to setup two CoreDNS deployments (via helm) to work as a primary-secondary setup for my homelab. 

Those are my values for the primary release:
```yaml
rbac:
  create: true
service:
  name: coredns-primary
servers:
- zones:
  - zone:
  port: 53
  plugins:
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  - name: etcd
    parameters: homelab.marfien.dev
    configBlock: |-
      stubzones
      path /skydns
      endpoint http://etcd.internal-dns.svc.cluster.local:2379
  - name: transfer
    configBlock: |
      to coredns-secondary.internal-dns.svc.cluster.local
```

And those for my secondary release:
```yaml
rbac:
  create: true
service:
  name: coredns-secondary
servers:
- port: 53
  plugins:
  - name: errors
  # Serves a /health endpoint on :8080, required for livenessProbe
  - name: health
    configBlock: |-
      lameduck 5s
  # Serves a /ready endpoint on :8181, required for readinessProbe
  - name: ready
  - name: secondary
    configBlock: |
      transfer from coredns-primary.internal-dns.svc.cluster.local
```

Both of them fail to start with a similar error message where it says that the <name>.<namespace>.dvc.cluster.local not a valid ip notation is:
```
plugin/transfer: must specify an IP address: `coredns-secondary.internal-dns.svc.cluster.local'
plugin/secondary: must specify an IP address: `coredns-primary.internal-dns.svc.cluster.local'
```

Any ideas how to solve this without using the literal ip?

Thanks in advance!
