### ISSUE TITLE
auto plugin complains about ConfigMap mounted volumes

### ISSUE THREAD

**Issue by particledecay** [coredns/coredns#1901]
To be clear, this is only when a ConfigMap is mounted without specifying individual items.

```yaml
    containers:
      - name: my-container
        volumeMounts:
          - name: zonedata
            mountPath: /etc/myzones
    volumes:
      - name: zonedata
        configMap:
          name: my-config
```

The files that are placed into `/etc/myzones` by Kubernetes may look like this:
```
/etc/myzones/example.com.db
/etc/myzones/example.org.db
```

However, those files are only symlinks to a directory whose name is a timestamp (set to the last datetime that the ConfigMap was updated):
```
/etc/myzones/example.com.db -> /etc/myzones/..data/example.com.db
/etc/myzones/..data -> /etc/myzones/..2018_06_27_07_11_05.442838727
```

Because the auto plugin performs a "walk", it will match the files in the timestamped subdirectory instead of the symlink (since `filepath.Walk` does not follow symbolic links). This means that as soon as the ConfigMap is updated and all the top-level symlinks are repointed to the latest timestamped subdirectory, CoreDNS will emit log messages stating that it can no longer find the zone that it previously read in the no-longer-existent files:

```
2018/06/27 14:46:30 [ERROR] plugin/file: Failed to open zone "example.com." in "/etc/myzones/..2018_06_27_07_11_05.442838727/example.com.db": open /etc/myzones/..2018_06_27_07_11_05.442838727/example.com.db: no such file or directory
```

This makes sense, because the file no longer exists. However, a new file now exists:
```
/etc/myzones/..2018_06_27_07_21_08.389576271/example.com.db
```
