### ISSUE TITLE
The service with IP as ExternalName did not work

### ISSUE THREAD

**Issue by zyxbest** [coredns/coredns#2164]
### My Env 
kubernetes v1.11.3 (HA cluster) + `k8s.gcr.io/coredns:1.1.3`  + aws 
### What I did
1. Create tests service  like this
```
---
kind: Service
apiVersion: v1
metadata:
  name: test-domain-service
spec:
  type: ExternalName
  externalName: kubernetes.io
---
kind: Service
apiVersion: v1
metadata:
  name: test-ip-service
spec:
  type: ExternalName
  externalName: 104.198.14.52
```

2. Enter (`kubectl exec`) one pod to access these services   
![image](https://user-images.githubusercontent.com/5809588/46609022-23437d00-cb39-11e8-960f-0ce7c0991bea.png)

### What I'm supposed to see (also works with kube-dns in kubeadm v1.6)
Kubernetes can resolve this two service as well

![image](https://user-images.githubusercontent.com/5809588/46609108-79182500-cb39-11e8-8a88-f91c7c787a41.png)

### What's more 
Actually, I want to create the service below:    
```
---
kind: Service
apiVersion: v1
metadata:
  name: test-domain-service
spec:
  type: ExternalName
  externalName: ip-10-10-10-204.xxxxxx.compute.internal
---
kind: Service
apiVersion: v1
metadata:
  name: test-ip-service
spec:
  type: ExternalName
  externalName: 10.10.10.204
```
As you see, they are aws EC2 private DNS name and private IP of one machine, the same result as the experiment.   

### My question 
Is there any feature or design that coreDns can't resolve service which forwards to an ip address?    
Similar question : https://discuss.kubernetes.io/t/service-externalname-ip/494/5

**Comment by chrisohaver** [comment]
It is unclear what you expect.  In your example, you say that "kubernetes can resolve these two service...", but in the graphic that follows it, both results are "Not Found" ...

It's odd that an IP is allowed in the "externalName" field.  The k8s documentation I found seems to infer that a IP in the field would not make sense:
>ExternalName: Maps the service to the contents of the externalName field (e.g. foo.bar.example.com), by returning a `CNAME` record with its value. No proxying of any kind is set up. This requires version 1.7 or higher of kube-dns. 

... AFIAK, a `CNAME` value cant be an IP.

If you want a service that resolves to a statically defined ip address, you could ...
* create a headless service
* then create a statically defined endpoint for that service that contains the ip address.

e.g.

```
apiVersion: v1
kind: Service
metadata:
  name: gdns
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: dns
    port: 53
    protocol: UDP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: gdns
  namespace: default
subsets:
  - addresses:
      - ip: 8.8.8.8
    ports:
      - port: 53
        name: dns
        protocol: UDP
```
