### ISSUE TITLE
plugin/kubernetes: Alias names for Services

### ISSUE THREAD

**Issue by chrisohaver** [coredns/coredns#2214]
Let's consider implementing something to facilitate kubernetes/kubernetes#39792.

kubernetes/kubernetes#39792 can be solved with rewrite rules (or with CNAMEs using `file` or `template`) for each alias. But these are cumbersome, and require ongoing maintenance to the Corefile or zonefile.  It may be more convenient to enable this via a Service annotation.

Could look something like the following, where k8s plugin looks for an annotation called "coredns.io/dnsAlias" ...

Add `mydomain.com` to k8s stanza in Corefile:
```
kubernetes cluster.local mydomain.com in-addr.arpa ip6.arpa {
  fallthrough mydomain.com in-addr.arpa ip6.arpa
}
```

Add annotation to a Service:
```
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: default
  annotations:
    coredns.io/dnsAlias: altname.mydomain.com
...
```

The _kubernetes_ plugin would see the `coredns.io/dnsAlias` and create `A`/`PTR` records for it.
