### ISSUE TITLE
plugin/kubernetes: ignore empty_service works incorrect for ExternalName services

### ISSUE THREAD

**Issue by ateleshev** [coredns/coredns#2688]
CoreDNS-1.4.0
---
Corefile:
```
    .:53 {
        errors
        health
        cache 30
        kubernetes test.local {
            ttl 30
            pods verified
            fallthrough
        }
        loadbalance round_robin
        prometheus 0.0.0.0:9153
        proxy . 10.10.10.10
    }
```
Service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test
    node: server1
  name: test-server1
  namespace: default
spec:
  externalName: 10-0-0-10.default.pod.test.local
  selector:
    app: test
    node: server1
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}

```
Check DNS:
```
root@test-bqlqw:/# nslookup test-server1
Server:         10.3.0.10
Address:        10.3.0.10#53

test-server1.default.svc.test.local  canonical name = 10-0-0-10.default.pod.test.local.
Name:   10-0-0-10.default.pod.test.local
Address: 10.0.0.10
```
Add ignore empty_service to Corefile:
```
    .:53 {
        errors
        health
        cache 30
        kubernetes test.local {
            ttl 30
            pods verified
            ignore empty_service   # <<<<<
            fallthrough
        }
        loadbalance round_robin
        prometheus 0.0.0.0:9153
        proxy . 10.10.10.10
    }
```
Result:
```
root@test-bqlqw:/# nslookup test-server1
Server:         10.3.0.10
Address:        10.3.0.10#53

** server can't find test-server1: NXDOMAIN
```
Another services works fine:
```
root@test-bqlqw:/# nslookup web-ui
Server:         10.3.0.10
Address:        10.3.0.10#53

Name:   web-ui.default.svc.test.local
Address: 10.0.0.177
```
