### ISSUE TITLE
Coredns not working on Android private DNS but works with IP query

### ISSUE THREAD

**Issue by msaeedm** [coredns/coredns#3229]
Hello, I am using CoreDNS-1.6.2 with the following Corefile:

```
tls://.:853 {
    errors
    tls fchain.pem key.pem
    # 192.168.1.180 is my pihole ip on my local network
    forward . dns://192.168.1.180
}
```
here are the last few lines from the log:
```
2019-08-29T23:48:50.919Z [INFO] CoreDNS-1.6.2
2019-08-29T23:48:50.919Z [INFO] linux/amd64, go1.12.8, 795a3eb
CoreDNS-1.6.2
linux/amd64, go1.12.8, 795a3eb
2019-08-29T23:49:21.085Z [INFO] 185.49.141.27:65404 - 23670 "A IN yahoo.com. tcp 128 false 65535" NOERROR qr,rd,ra 278 0.036626189s
2019-08-29T23:49:37.031Z [INFO] 185.49.141.27:58080 - 33236 "A IN msn.com. tcp 128 false 65535" NOERROR qr,rd,ra 135 0.133684711s
```

Here is my docker-compose file
```
version: '3.4'
services:
  coredns:
    container_name: coredns
    image: coredns/coredns:latest
    restart: always  
    domainname: foo.mydomain.tld
    hostname: coredns
    ports:
      - target: 853
        published: 853
        protocol: tcp
        mode: host        
    volumes:
      - ./coredns/config/Corefile:/Corefile:ro
      - ./coredns/config/plugin.cfg:/plugin.cfg:ro
      # my self signed certificate
      - ./keys/foo.mydomain.tld.crt:/fchain.pem:ro
      - ./keys/foo.mydomain.tld.pem:/key.pem:ro
```

Other possibly relevant info:

1. my domain is managed by cloudflare. I created a CNAME entry to foo.mydomain.tld which is not proxied (dns-only).

2. When I try to query through [getdns](https://getdnsapi.net/query/) using transport order "TLS" and my external IP for "TLS resolver IP", I get a good response such as what is shown in the log. 

3. I tried both a self signed certificate and also cloudflare's universal certificate. no difference noted.

When I use foo.mydomain.tld on Android private DNS nothing shows in the logs and no DNS requests are resolved?! 

Would you please help me find why Android Pie private DNS not working for me?

Thank you,
