### ISSUE TITLE
Not resolving custom domain other than *.global

### ISSUE THREAD

**Issue by rjshrjndrn** [coredns/coredns#3384]
### Issue
I've Coredns in kube-system and istiocoredns in istio-system namespace
1. When I try to create a serviceentry, I want that to be globally resolvable in cluster
2. For that I added some entries in coredns config

Issue is *.global is working but *.dev is not working

corefile 
```
.:53 {
        errors
        health
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          upstream
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          reload 1s
          fallthrough
        }
        prometheus :9153
        proxy . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
    dev:53 {
       errors
       cache 30
       forward . 10.43.203.190
    }
    global:53 {
       errors
       cache 30
       forward . 10.43.203.190
    }
```

dns queries should forward both *.dev and *.global to istio core-dns.
*.global is working fine
```
root@dnsutils:/# host keycloak.sunbird.global
keycloak.sunbird.global has address 11.2.0.129
Host keycloak.sunbird.global not found: 3(NXDOMAIN)
Host keycloak.sunbird.global not found: 3(NXDOMAIN)
root@dnsutils:/# dig keycloak.sunbird.global

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> keycloak.sunbird.global
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29782
;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;keycloak.sunbird.global.       IN      A

;; ANSWER SECTION:
keycloak.sunbird.global. 8      IN      A       11.2.0.129

;; Query time: 0 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Fri Oct 18 07:24:20 UTC 2019
;; MSG SIZE  rcvd: 91

```
But *.dev is not working
```
root@dnsutils:/# host keycloak.test.dev
Host keycloak.test.dev not found: 3(NXDOMAIN)
root@dnsutils:/# dig keycloak.test.dev

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> keycloak.test.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 62228
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;keycloak.test.dev.             IN      A

;; AUTHORITY SECTION:
dev.                    10      IN      SOA     ns-tld1.charlestonroadregistry.com. cloud-dns-hostmaster.google.com. 1 21600 3600 259200 300

;; Query time: 0 msec
;; SERVER: 10.43.0.10#53(10.43.0.10)
;; WHEN: Fri Oct 18 07:25:28 UTC 2019
;; MSG SIZE  rcvd: 150

root@dnsutils:/#
```

Am I missing anything

**Additional info**

`*.dev serviceentry`
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: keycloak-test
spec:
  hosts:
  - 'keycloak.test.dev'
  addresses:
  - 11.2.0.129
  ports:
  - number: 8080
    name: keycloak
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
  - address: 11.2.0.129
```
`*.global serviceentry`
```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: keycloak-test
spec:
  hosts:
  - 'keycloak.test.global'
  addresses:
  - 11.2.0.129
  ports:
  - number: 8080
    name: keycloak
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
  - address: 11.2.0.129
```
