### ISSUE TITLE
CoreDNS pods crashing if resolv-conf is configured in kubelet configfile instead of systemd

### ISSUE THREAD

**Issue by Skull0ne** [coredns/coredns#3700]
**What happened**:
--resolv-conf parameter in kubelet service is deprecated since 1.10 . I moved it in my configuration file defined in my --config parameter of my kubelet systemd script but the coredns pods start crashing 

**What you expected to happen**:
Pods should be able to use the config defined in the --config parameter

**How to reproduce it (as minimally and precisely as possible)**:
Using kubernetes 1.14, define the resolv conf in a config file instead of the systemd script.

**Environment**:

- the version of CoreDNS: coredns/coredns:1.5.0
- Corefile:
```
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```
- logs, if applicable:
```
.:53
2020-02-27T15:13:58.070Z [INFO] plugin/reload: Running configuration MD5 = 76dd40a8d85f49bc080c15939532be01
2020-02-27T15:13:58.070Z [INFO] CoreDNS-1.5.0
2020-02-27T15:13:58.071Z [INFO] linux/amd64, go1.12.2, e3f9a80
CoreDNS-1.5.0
linux/amd64, go1.12.2, e3f9a80
2020-02-27T15:13:58.071Z [FATAL] plugin/loop: Loop (127.0.0.1:56570 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 7429025918858587052.2020514849626621078."
```
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.1 LTS
- Others: 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
```

Thanks

**Comment by miekg** [comment]
You have created a resolving loop. See multiple previous and identical
issues

/close

**Comment by Skull0ne** [comment]
This is not the issue here... The issue is the fact that coredns can't use the config provided in the config file.
kube-kubelet.service : 
```
[Unit]
Description=Kubernetes Kubelet Server
Documentation=https://kubernetes.io/docs/concepts/overview/components/#kubelet https://kubernetes.io/docs/reference/generated/kubelet/
Requires=setup-network-environment.service docker.service
After=setup-network-environment.service docker.service

[Service]
EnvironmentFile=/etc/network-environment
ExecStartPre=/bin/cp \
  "/usr/local/bin/kubelet_v1.14.1_c9f08323107a960b9ce075f1bee116dc9cedf7a5faea54e96ecfaf6399f6e5a3" \
  "/usr/local/bin/kubelet"
# wait for kubernetes master to be up and ready
ExecStart=/usr/local/bin/kubelet \
  --config=/etc/kubernetes/config \
  --node-ip=10.x.x.x \
  --hostname-override=xxxxxxxxxxx \
  --kubeconfig=/etc/kubernetes/ssl/xxxxxxxxxxx.kubeconfig.yml \
  --logtostderr=false \
  --log-file=/var/log/kubelet.log \
  --cloud-provider=gce \
  --cloud-config=/etc/kubernetes/cloud-config \
  --authentication-token-webhook \
  --network-plugin=cni \

#  --resolv-conf=/run/systemd/resolve/resolv.conf \

Restart=on-failure
RestartSec=5
TimeoutStartSec=600

[Install]
WantedBy=multi-user.target
```

/etc/kubernetes/config : 
```
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
address: 10.x.x.x
tlsPrivateKeyFile: /etc/kubernetes/ssl/xxxxxxxxxx.key.pem
tlsCertFile: /etc/kubernetes/ssl/xxxxxxxxxx.pem
clientCAFile: /etc/kubernetes/ssl/ca.pem
port: 10250
healthzPort: 10248
healthzBindAddress: 0.0.0.0
clusterDomain: cluster.local
clusterDNS: [ 10.100.0.10 ]
maxPods: 400
authentication:
  anonymous:
    enabled: false # Defaults to false as of 1.10
  webhook:
    enabled: false # Defaults to true as of 1.10
  x509:
    clientCAFile: /etc/kubernetes/ssl/ca.pem
authorization:
  mode: AlwaysAllow # Defaults to Webhook as of 1.10
resolvconf: /run/systemd/resolve/resolv.conf #not sure about this parameter, tried this one and resolverconfig (https://github.com/coredns/coredns/tree/master/plugin/loop#troubleshooting-loops-in-kubernetes-clusters & https://godoc.org/k8s.io/kubelet/config/v1beta1)
```

If I use the --resolv-conf parameter in the service file it's working.
