### ISSUE TITLE
coredns is returning multiple records when one record is expected.

### ISSUE THREAD

**Issue by gaddamas** [coredns/coredns#3803]
**What happened**:
configured external-dns to use coredns with etcd backend.
In kubernets cluster created an ingress with host 'mycluster.example.com' 
and two services 'service1.mycluster.example.com', 'service2.mycluster.example.com'
nslookup of mycluster.example.com is returning all three addresses.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui
  namespace: default
spec:
  rules:
  - host: mycluster.example.com
---
apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: service1.mycluster.example.com
---
apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: service2.mycluster.example.com
```
external-dns created entries in coredns etcd backend for ingress and two services

ETCDCTL_API=3 etcdctl get --prefix=true "" --endpoints http://10.243.86.17:2379  | grep mycluster
```
/skydns/com/example/mycluster/14308af3
{"host":"10.xxx.xx.111","text":"\"heritage=external-dns,external-dns/owner=mycluster-example-com,external-dns/resource=ingress/default/ui\"","targetstrip":1}
/skydns/com/example/mycluster/default/service1/55b88aa2
{"host":"10.xxx.xx.114","text":"\"heritage=external-dns,external-dns/owner=mycluster-example-com,external-dns/resource=service/default/service1\"","targetstrip":1}
/skydns/com/example/mycluster/default/service2/7b10736e
{"host":"10.xxx.xx.115","text":"\"heritage=external-dns,external-dns/owner=mycluster-example-com,external-dns/resource=service/default/service2\"","targetstrip":1}
```
nslookup returned entries for services correctly, however for the ingress using mycluster.example.com three entries are returned
```
nslookup service1.mycluster.example.com 10.xxx.xx.17
Server:		10.xxx.xx.17
Address:	10.xxx.xx.17#53

Name:	service1.mycluster.example.com
Address: 10.xxx.xx.114
---
nslookup service2.mycluster.example.com 10.xxx.xx.17
Server:		10.xxx.xx.17
Address:	10.xxx.xx.17#53

Name:	service2.mycluster.example.com
Address: 10.xxx.xx.115
---
nslookup mycluster.example.com 10.xxx.xx.17
Server:		10.xxx.xx.17
Address:	10.xxx.xx.17#53

Name:	mycluster.example.com
Address: 10.xxx.xx.111
Name:	mycluster.example.com
Address: 10.xxx.xx.114
Name:	mycluster.example.com
Address: 10.xxx.xx.115

```

**What you expected to happen**:
expecting nslookup return only one entry for ingress endpoint.
when multiple IPs are returned our 'ui'  is failing sometimes when client picks up wrong address.
```
nslookup mycluster.example.com 10.xxx.xx.17
Server:		10.xxx.xx.17
Address:	10.xxx.xx.17#53

Name:	mycluster.example.com
Address: 10.xxx.xx.111
```

**How to reproduce it (as minimally and precisely as possible)**:
see steps above to create entries

**Anything else we need to know?**:

Looked into coredns documentation, it says it is a special behavior
https://github.com/coredns/coredns/tree/master/plugin/etcd#special-behaviour
looks like lookup of toplevel domain causes it recurse the hierarchy (or prefix) and returning all the entries.
When using AWS Route53 or Google CloudDNS, we get one response for lookups to mycluster.example.com correctly returning address 10.xxx.xx.111

One alternative I find is to add ui prefix my ingress host, like
ui.mycluster.example.com, but it is not very appealing for our users.

**Environment**:

- the version of CoreDNS: 1.6.2, etcd: 3.3.15
- Corefile: 
```
.:53 {
    errors
    log
    etcd example.com.com:53 {
        path /skydns
        endpoint http://10.xxx.xx.17:2379
        fallthrough
    }
    hosts /etc/coredns/hosts {
        fallthrough
    }
    forward . 10.xxx.xx.108:53
    cache 120
}
```
- logs, if applicable:
- OS (e.g: `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
- Others:
