### ISSUE TITLE
localEndpoint is missing in span, in tracer plugin

### ISSUE THREAD

**Issue by nemanjan00** [coredns/coredns#4160]
**What happened**:

When sending trace to zipkin, localEndpoint is missing and result of that is the name of service is "unknown-service-name" when sending trace to jaeger. 

**What you expected to happen**:

Jaeger expects localEndpoint that looks something like this:

```
    "localEndpoint": {
      "serviceName": "backend",
      "ipv4": "192.168.99.1",
      "port": 3306
    },
```

It is expected to have `localEndpoint` object with `serviceName` that is the same as service name from config, but, `localEndpoint` is missing. 

**How to reproduce it (as minimally and precisely as possible)**:

Just send trace to jaeger. 

docker-compose.yml

```
version: '3.5'

services:
  dns:
    image: coredns/coredns:latest

    command: ["-conf", "/config/Corefile"]

    ports:
      - "53:53/udp"

    volumes:
      - ./Corefile:/config/Corefile

  jaeger:
    image: 'jaegertracing/all-in-one:1.8'
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - '8086:8086'
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686' 
      - '14268:14268'
      - '9411:9411'
```

Corefile

```
. {
  whoami
  health

  trace zipkin jaeger:9411 {
    service dns
  }
}
```

**Anything else we need to know?**:

**Environment**:

- the version of CoreDNS: linux/amd64, go1.15.2, aa82ca6 
- Corefile: 

```
. {
  whoami
  health

  trace zipkin jaeger:9411 {
    service dns
  }
}
```
