### ISSUE TITLE
plugin/forward: not an IP address or file:dc-consul-agent-dns.default.svc.cluster.local

### ISSUE THREAD

**Issue by s-u-b-h-a-k-a-r** [coredns/coredns#4500]
**What happened**:
We are trying to implement consul dns as specified in the below link
https://www.consul.io/docs/k8s/dns
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        <Existing CoreDNS definition>
    }
  consul {
    errors
     cache 30
    forward . <consul-dns-service-cluster-ip>
   }
```

**What you expected to happen**:
We are trying to give the service name since it will not be changed where as ClusterIP will be keep on changing when we delete and redeploy.
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        <Existing CoreDNS definition>
    }
  consul {
    errors
     cache 30
    forward . dc-consul-agent-dns.default.svc.cluster.local
   }
```
But the above change giving service name is working file for existing pod which was running.
But whenever we are trying to bring new pod it throws the below error.
**_plugin/forward: not an IP address or file: dc-consul-agent-dns.default.svc.cluster.local_**

When the above coredns configmap changed to point to ClusterIP works

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        <Existing CoreDNS definition>
    }
  consul {
    errors
     cache 30
    forward . 10.42.29.19
   }
```

**Environment**:
Kubernetes Version: v1.17.13
- the version of CoreDNS:
  coredns:1.6.5
- Corefile:
- logs, if applicable:
plugin/forward: not an IP address or file: dc-consul-agent-dns.default.svc.cluster.local
it throws the below error
