### ISSUE TITLE
Notify messages not accepted by NSD

### ISSUE THREAD

**Issue by falzm** [coredns/coredns#640]
Hi

I'm trying CoreDNS set up as a "hidden" DNS master with a NSD server slave of the CoreDNS – using the middleware `file` for tests. Although NSD is able to fetch the DNS zone from by CoreDNS via AXFR, notify messages sent by CoreDNS don't seem to be accepted by NSD. Here is the error message I get when I edit the zone on CoreDNS (no logs at NSD level):

```
2017/04/21 23:47:44 [INFO] Successfully reloaded zone `myzone.local.'
2017/04/21 23:47:44 [ERROR] Notify for zone "myzone.local." was not accepted by "127.0.0.3:53": "dns: failed to unpack truncated message"
```

Corefile:

```
.:53 {
    bind 127.0.0.2
    errors stdout
    log stdout
    health
    file /Users/marc/dev/coredns/myzone.local myzone.local {
        transfer to *
        transfer to 127.0.0.3
    }
}
```

NSD configuration:

```
server:
    ip-address: 127.0.0.3
    port: 53

zone:
    name: "myzone.local"
    request-xfr: 127.0.0.2@53 NOKEY
    allow-notify: 127.0.0.2 NOKEY
```

Tested with NSD 4.1.15 on macOS with CoreDNS v006 (Golang 1.8.x). Let me know if you need me to provide more information.
