### ISSUE TITLE
crun: chdir to `/home/nonroot`: Permission denied: OCI permission denied

### ISSUE THREAD

**Issue by micheelengronne** [coredns/coredns#6719]
**What happened**:

While trying to run coredns in a rootless and subuid/subgid environment, the container can not start:

`crun: chdir to `/home/nonroot`: Permission denied: OCI permission denied`

**What you expected to happen**:

the container to start

**How to reproduce it (as minimally and precisely as possible)**:

Run it with th environment described below.

**Anything else we need to know?**:

Replace nonroot USER by a UID and give /home/nonroot group permissions similar to user permissions, that way we can add it as an additional group in the security context.

**Environment**:

podman with "userns": "auto:gidmapping=1002:33002:1,uidmapping=1002:33002:1" and securitycontext with:

```
 securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1002
    runAsGroup: 1002
    capabilities:
      drop:
      - all
```

- the version of CoreDNS: 1.11.1
