### ISSUE TITLE
CoreDNS locking up (and memory balooning) while resolving addresses from Azure Private Zones

### ISSUE THREAD

**Issue by weakcamel** [coredns/coredns#7316]
**What happened**:

Our instance(s) of CoreDNS are mostly configured to resolve addresses for the internal infrastructure based on the content of Azure Private DNS zones. There's a fallback to public DNS servers for other queries (to 1.1.1.1, 8.8.8.8, 9.9.9.9)

After some time of running (it used to be ~2 weeks but time is shortening recently to 1-2 days (or a few hours if we disable the CoreDNS caching the records), CoreDNS just stops answering queries for the zones we host (some or all of them) entirely - all queries for those zones time out.

At the same time we're observing memory consumption growing significantly to several GiB, eventually leading to OOM Killer kicking in and killing CoreDNS process.

```
$ sudo docker stats --no-stream
CONTAINER ID   NAME            CPU %     MEM USAGE / LIMIT     MEM %     NET I/O          BLOCK I/O     PIDS
bf0b44a90b88   dns-coredns-1   1.12%     6.473GiB / 31.34GiB   20.65%    1.26GB / 1.5GB   10.2MB / 0B   9
```

OS memory graph (from Node Exporter) - there's nothing else but CoreDNS running on this VM

Test was started ~18:00 and lasted for 10 hours (when the memory balooning slows down)

![Image](https://github.com/user-attachments/assets/02742322-9db5-4c1b-8656-3ca892f33a2a)

**What you expected to happen**:

Just normal operation, addresses resolved.

**How to reproduce it (as minimally and precisely as possible)**:

It's a bit tricky to reproduce :( but disabling caching seems to have helped a lot to speed it up.
We're basically running [dnsprof](https://github.com/DNS-OARC/dnsperf) tool against it with a sample of recorded traffic; traffic consists mostly of queries for our internal addresses + some Internet hosts.

`dnsprof` is replaying some fairly low traffic (1000 queries per second) and this is a sample 10h run:

```
$ dnsperf -f inet -m udp -d dns02_sample_clean.txt -l 36000 -s 172.21.34.114 -Q 1000 -S 60

...


Statistics:

  Queries sent:         5415840
  Queries completed:    4797366 (88.58%)
  Queries lost:         618474 (11.42%)

  Response codes:       NOERROR 4582298 (95.52%), SERVFAIL 11 (0.00%), NXDOMAIN 214952 (4.48%), NOTIMP 105 (0.00%)
  Average packet size:  request 47, response 105
  Run time (s):         36000.000282
  Queries per second:   133.260166

  Average Latency (s):  0.000827 (min 0.000131, max 2.017172)
  Latency StdDev (s):   0.010035
```

**Anything else we need to know?**:

I currently have a VM with CoreDNS in "hanging" state - queries time out for our zones but succeed when looking up Internet hosts. 

```
$ nslookup google.co.uk 172.21.34.114
Server:         172.21.34.114
Address:        172.21.34.114#53

Non-authoritative answer:
Name:   google.co.uk
Address: 108.177.127.94
Name:   google.co.uk
Address: 2a00:1450:4013:c07::5e

$ nslookup myzone.io 172.21.34.114
;; communications error to 172.21.34.114#53: timed out
;; communications error to 172.21.34.114#53: timed out
;; communications error to 172.21.34.114#53: timed out
;; no servers could be reached

```

We've managed to also enable [pprof](https://coredns.io/plugins/pprof/) and get some results out of it (with help from a friendly Go developer) - just in case that sheds some light on the situation.

![Image](https://github.com/user-attachments/assets/751bdf03-e84c-44a9-a264-7067da4c5da8)

![Image](https://github.com/user-attachments/assets/ae29b7e0-b951-4eb6-9bbc-eb7c9ccd37d0)

**Environment**:

- the version of CoreDNS: **v1.12.1**
- logs, if applicable:
  -  **in the locked up state, the queries for hosted zones don't get logged at all. No errors  logged either**.
- OS (e.g: `cat /etc/os-release`): **Ubuntu 22.04.5 LTS**
- Others:
  - **CoreDNS running in a Docker container (NOT in Kubernetes) with docker-compose**

```yaml
---
services:
  coredns:
    image: docker.io/coredns/coredns:1.12.1
    volumes:
      - ./config:/config:ro
    command: >-
      -conf /config/Corefile
    environment:
      GOMAXPROCS: 2
    env_file:
      - .env
    ports:
      - 53:53/tcp
      - 53:53/udp
      # Health endpoint - `/health`
      - 8080:8080/tcp
      # Readiness endpoint - `/ready`
      - 8181:8181/tcp
      # Prometheus endpoint - `/metrics`
      - 9153:9153/tcp
      # Pprof endpoint - /debug/pprof
      - 6053:6053/tcp
    logging:
      driver: journald
      options:
        tag: "{{.Name}}"
    restart: always
```

- Corefile: heavily redacted, we've got a bunch of files for all the hosted zones; this is just to give the feel 

```
# Corefile
import common.conf

import azure-dev/main.conf
import azure-dev/zones/forward/*.conf
### ... snip ...
import forwarder/main.conf
```

```
# common.conf
(common-no-cache) {
  log . {combined}
  # https://coredns.io/plugins/debug
  # "errors" negates the "debug" behaviour but side effect
  # of debug logs stays
  debug
  errors
  reload 10s
  ready
  prometheus 0.0.0.0:9153
  pprof 0.0.0.0:6053
}

(common) {
  import common-no-cache
  # cache 120
  # cache 30
}

(authoritative) {
  header {
    response set ra
  }
}
```

```
# forwarder/main.conf - fallback for public addresses
. {
  import common
  health :8080
  forward . 1.1.1.1 8.8.8.8 9.9.9.9
}
```

```
# azure-dev/zones/forward/myzone.io.conf
myzone.io {
  import common
  import authoritative

  azure private-dns-colo-forward:core.myzone.io {
    import az-platform-dev
  }
  azure private-dns-colo-forward:desktops.myzone.io {
    import az-platform-dev
  }
# ... SNIP
```
